=== nasa-gcn/gcn-avro-schema/gcn/notices/core/Statistics.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://gcn.nasa.gov/schema/main/gcn/notices/core/Statistics.schema.json",
  "title": "Statistics",
  "description": "statistical measures of source significance or classification",
  "type": "object",
  "properties": {
    "properties": {
      "description": "Dictionary of binary classifiers, each entry is between 0 and 1. e.g. ({'NS', 0.95}, {'REMNANT', 0.3})",
      "type": "object",
      "additionalProperties": {
        "type": "number"
      }
    },
    "backgound_count_rate": {
      "description": "Count rate of the background during the transient [counts/s] over same rate_duration and rate_energy_range used for net_count_rate.",
      "type": "number"
    },
    "classification": {
      "description": "Dictionary mapping mutually exclusive source classes to probabilities between 0 and 1, the sum of all values must be 1. e.g. ({'BNS', 0.9}, {'NSBH', 0.05}, {'BBH', 0.05})",
      "type": "object",
      "additionalProperties": {
        "type": "number"
      }
    },
    "far": {
      "description": "False alarm rate: the rate of occurrence of non-astrophysical events that are of the same intensity or significance as the current event [Hz]",
      "type": "number"
    },
    "image_duration": {
      "description": "Interval over image signal to noise ratio calculation [s]",
      "type": "number"
    },
    "image_energy_range": {
      "description": "Low and High energy bounds used in image signal to noise ratio calculation, if not parsed in Reporter.schema.json, default unit is keV",
      "type": "array",
      "maxItems": 2,
      "minItems": 2,
      "items": {
        "type": "number"
      }
    },
    "image_snr": {
      "description": "Image signal to noise ratio [dimensionless]",
      "type": "number"
    },
    "net_count_rate": {
      "description": "Net count rate of the transient above the background [counts/s] over rate_duration and rate_energy_range. Do specify rate_duration and rate_energy_range with net_count_rate property.",
      "type": "number"
    },
    "p_astro": {
      "description": "Probability [dimensionless, 0-1] that source is of astrophysical origin",
      "type": "number"
    },
    "rate_duration": {
      "description": "Interval over rate signal to noise ratio calculation [s]",
      "type": "number"
    },
    "rate_energy_range": {
      "description": "Low and High energy bounds used in rate signal to noise ratio calculation, if not parsed in Reporter.schema.json, default unit is keV",
      "type": "array",
      "maxItems": 2,
      "minItems": 2,
      "items": {
        "type": "number"
      }
    },
    "rate_snr": {
      "description": "Rate signal to noise ratio [dimensionless]",
      "type": "number"
    },
    "trigger_type": {
      "description": "Type of trigger algorithm used to identify the transient event.",
      "enum": [
        "rate",
        "image"
      ]
    }
  }
}

=== nasa-gcn/gcn-avro-schema/gcn/notices/core/Statistics.example.json
{
  "$schema": "https://gcn.nasa.gov/schema/main/gcn/notices/core/Statistics.schema.json",
  "far": 0.001,
  "rate_snr": 5.2,
  "rate_duration": 10,
  "rate_energy_range": [100, 1000],
  "image_snr": 3.1,
  "image_duration": 30,
  "image_energy_range": [50, 500],
  "p_astro": 0.8,
  "classification": {
    "BNS": 0.9,
    "NSBH": 0.05,
    "BBH": 0.05
  },
  "properties": {
    "NS": 0.95,
    "REMNANT": 0.05
  }
}
