=== nasa-gcn/gcn-avro-schema/gcn/notices/icecube/amon/GoldAndBronze.schema.json
{
  "$id": "https://gcn.nasa.gov/schema/gcn/notices/icecube/amon/GoldAndBronze.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "GoldAndBronze",
  "description": "GoldAndBronze events",
  "properties": {
    "type": {
      "description": "Notice type Gold or Bronze",
      "type": "string"
    },
    "event": {
      "$ref": "/schema/gcn/notices/core/Names.schema.json"
    },
    "localization": {
      "$ref": "/schema/gcn/notices/core/Localization.schema.json"
    },
    "err50": {
      "description": "Location uncertainty (radius, 50% containment) in units of arcmin",
      "type": "number",
      "minimum": 0
    },
    "discovery_datetime": {
      "$ref": "/schema/gcn/notices/core/DateTime.schema.json"
    },
    "revision": {
      "description": "Revision number by IceCube",
      "type": "number"
    },
    "energy": {
      "description": "Most probable neutrino energy [TeV] that would have produced an event",
      "type": "number",
      "minimum": 0
    },
    "signalness": {
      "description": "Probability [dn] that this is an astrophysical signal relative to backgrounds",
      "type": "number",
      "minimum": 0
    },
    "far": {
      "description": "Rate of background events expected that are 'like this alert', would be seen by IceCube per year",
      "$ref": "/schema/gcn/notices/core/Statistics.schema.json"
    }
  },
  "required": [
    "type",
    "event",
    "localization",
    "err50",
    "discovery_datetime",
    "revision",
    "energy",
    "signalness",
    "far"
  ]
}

=== nasa-gcn/gcn-avro-schema/gcn/notices/icecube/GoldAndBronze.example.json
{
  "$schema": "https://gcn.nasa.gov/schema/gcn/notices/icecube/GoldAndBronze.schema.json",
  "type": "Gold",
  "event": {
    "event_name": ["GRB", "GW"],
    "id": ["120", "131"]
  },
  "localization": {
    "ra": 0,
    "dec": 0,
    "semi_major": 0,
    "semi_minor": 0,
    "position_angle": 0,
    "containment_probability": 0,
    "systematic_included": true,
    "healpix_url": "url.example.com"
  },
  "err50": 0,
  "discovery_datetime": {
    "trigger_time": "ISO 8601 time here",
    "observation_start": "ISO 8601 time here",
    "observation_stop": "ISO 8601 time here",
    "observation_livetime": 0
  },
  "revision": 0,
  "energy": 0,
  "signalness": 0,
  "far": {
    "far": 0,
    "rate_snr": 0,
    "rate_duration": 0,
    "rate_energy_range": {
      "energy_low": 0,
      "band": "energy",
      "units": "keV",
      "energy_high": 0
    },
    "image_snr": 0,
    "image_duration": 0,
    "image_energy_range": {
      "energy_low": 0,
      "band": "energy",
      "units": "keV",
      "energy_high": 0
    },
    "p_astro": 0,
    "classification": {
      "type": 0
    },
    "properties": {
      "type": "object"
    }
  }
}
