=== nasa-gcn/gcn-avro-schema/gcn/notices/swift/bat/guano/alert.schema.json
{
  "$id": "https://gcn.nasa.gov/schema/gcn/notices/swift/bat/guano/alert.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "reporter": {
      "$ref": "/schema/gcn/notices/core/Reporter.schema.json"
    },
    "alert": {
      "$ref": "/schema/gcn/notices/core/Alert.schema.json"
    },
    "event": {
      "$ref": "/schema/gcn/notices/core/Event.schema.json"
    },
    "datetime": {
      "$ref": "/schema/gcn/notices/core/DateTime.schema.json"
    },
    "localization": {
      "$ref": "/schema/gcn/notices/core/Localization.schema.json"
    },
    "statistics": {
      "$ref": "/schema/gcn/notices/core/Statistics.schema.json"
    }
  },
  "required": ["reporter", "alert", "event", "datetime"]
}

=== nasa-gcn/gcn-avro-schema/gcn/notices/swift/bat/guano/loc-arcmin.example.json
{
  "$schema": "https://gcn.nasa.gov/schema/gcn/notices/swift/bat/guano/alert.schema.json",
  "reporter": {
    "mission": "Swift",
    "instrument": "BAT-GUANO",
    "record_number": 3
  },
  "alert": {
    "alert_datetime": "[UTC, ISO 8601]",
    "alert_tense": "current",
    "alert_type": "update"
  },
  "datetime": {
    "trigger_time": "Time of the trigger [ISO 8601]"
  },
  "localization": {
    "ra": 193.8,
    "dec": 37.6,
    "semi_major": 0.03,
    "containment_probability": 0.9,
    "systematic_included": true
  },
  "statistics": {
    "rate_snr": 7.5,
    "rate_duration": 0.256,
    "rate_energy_range": {
      "energy_low": 15,
      "energy_high": 350
    },
    "image_snr": 6,
    "image_duration": 0.256,
    "image_energy_range": {
      "energy_low": 15,
      "energy_high": 350
    },
    "classification": { "GRB": 1 }
  },
  "event": {
    "data_archive_page": "https://swift.gsfc.nasa.gov/archive/",
    "instrument_id": "700000031",
    "instrument_id_alternate": "7000000000"
  }
}

=== nasa-gcn/gcn-avro-schema/gcn/notices/swift/bat/guano/retraction.example.json
{
  "$schema": "https://gcn.nasa.gov/schema/gcn/notices/swift/bat/guano/alert.schema.json",
  "reporter": {
    "mission": "Swift",
    "instrument": "BAT-GUANO",
    "record_number": 4
  },
  "alert": {
    "alert_datetime": "[UTC, ISO 8601]",
    "alert_tense": "current",
    "alert_type": "retraction"
  },
  "datetime": {
    "trigger_time": "Time of the trigger [ISO 8601]"
  },
  "event": {
    "data_archive_page": "https://swift.gsfc.nasa.gov/archive/",
    "Id": "[700000031, 7000000000]"
  }
}
